[project]
name = "html-parser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "brotli>=1.2.0",
    "curl-cffi>=0.15.0",
    "html2text>=2025.4.15",
    "playwright>=1.59.0",
    "requests>=2.34.0",
]
